### ISSUE TITLE
Possible problem with `save_dir` vs. `save_path`

### ISSUE THREAD

**Issue by wtaylor17** [varnio/fedsim#22]
The base `DataManager` class takes a `save_dir` keyword argument, but subclasses (e.g. `BasicDataManager`, `CustomDataManager`) rely on a `save_path` keyword argument, and passes it to the super class (which absorbs it via `**kwargs`, making it "fail silently"). It likely should be changed so all classes rely on only one of these two keyword arguments. @fvarno what are your thoughts on this?

**Comment by fvarno** [comment]
That is a superb catch! I'll make a commit.
